contact/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import url
from .import views
from .views import *
from django.conf import settings


app_name = 'contact'
urlpatterns = [
        path('', views.CalendarView.as_view() , name="index"),
        url(r'^calendar/$', views.CalendarView.as_view(), name='calendar'),
        url(r'^event/new/$', views.event, name='event_new'),
	url(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),  

        
        path('message/', views.MessageView.as_view() , name="message-create"),
        path('event/<str:d>', views.EventView.as_view() , name="event-check"),


        
        path('accounts/login/', index, name='loginview'),
]

pivotora/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("contact.urls")),
    re_path('^admin/', admin.site.urls),

    re_path(r'^admin/password_reset/$',auth_views.PasswordResetView.as_view(),name='admin_password_reset'),
    re_path(r'^admin/password_reset/done/$',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    re_path(r'^reset/done/$',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
    re_path(r'^password/change/$',
    auth_views.PasswordChangeView.as_view(),
    name='auth_password_change'),
    re_path(r'^password/change/done/$',
    auth_views.PasswordChangeDoneView.as_view(),
    name='auth_password_change_done'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/models.py
from django.db import models
from django.urls import reverse

class Event(models.Model):
    email = models.CharField(max_length=100)
    date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()
    approved = models.BooleanField(default=False)


    @property
    def get_html_url(self):
        url = reverse('contact:event_edit', args=(self.id,))
        return f'<a href="{url}"> abc </a>'


class Message(models.Model):
    name = models.CharField(max_length=60)
    email = models.CharField(max_length=60)
    message = models.TextField()
    resolved = models.BooleanField(default=False)
    sent_at = models.DateTimeField(auto_now_add=True)

class WebContent(models.Model):
    about_us = models.TextField()
    mission =  models.TextField()
    email1 = models.TextField()
    email2 = models.TextField()
    speciality_image = models.ImageField(upload_to='',null=True,default='img/abc.jpg', blank=True) 

    @property
    def image_url(self):
        if self.speciality_image and hasattr(self.speciality_image, 'url'):
            return self.speciality_image 

class Portfolio(models.Model):
    title_image = models.ImageField(null=True,default='img/abc.jpg', blank=True)    
    short_description = models.TextField()

    @property
    def image_url(self):
        if self.title_image and hasattr(self.title_image, 'url'):
            return self.title_image

contact/forms.py
from django.forms import ModelForm, DateInput
from .models import Event

class EventForm(ModelForm):
  class Meta:
    model = Event
    # datetime-local is a HTML5 input type, format to make date time show on fields
    widgets = {
      'start_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
      'end_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
    }
    fields = '__all__'

  def __init__(self, *args, **kwargs):
    super(EventForm, self).__init__(*args, **kwargs)
    # input_formats parses HTML5 datetime-local input to datetime field
    self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
    self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)

contact/views.py
from django.views import View
from .models import *
from django.shortcuts import render, redirect,reverse
from django.utils.decorators import method_decorator
from datetime import datetime, timedelta, date
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.utils.safestring import mark_safe
from django.utils.dateparse import parse_datetime
import calendar
from .models import *
from .utils import Calendar
from contact.forms import EventForm


# Create your views here.
class PivotoraIndex(View):
    template_name = "index.html"

    def get(self, request):
        web_content = WebContent.objects.filter().first()
        portfolio = Portfolio.objects.all()
        context = {
            'content': web_content,
            'portfolio': portfolio

        }
        return render(request, self.template_name, context)





class CalendarView(generic.ListView):
    model = Event
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        web_content = WebContent.objects.filter().first()
        portfolio = Portfolio.objects.all()
        context = {
            'content': web_content,
            'portfolio': portfolio

        }
        d = get_date(self.request.GET.get('month', None))
        cal = Calendar(d.year, d.month)
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context

def get_date(req_month):
    if req_month:
        year, month = (int(x) for x in req_month.split('-'))
        return date(year, month, day=1)
    return datetime.today()

def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month

def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month

def event(request, event_id=None):
    instance = Event()
    if event_id:
        instance = get_object_or_404(Event, pk=event_id)
    else:
        instance = Event()

    form = EventForm(request.POST or None, instance=instance)
    if request.POST and form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('contact:calendar'))
    web_content = WebContent.objects.filter().first()
    portfolio = Portfolio.objects.all()
    context = {
        'content': web_content,
        'portfolio': portfolio,
        'form': form

    }
    return render(request, 'index.html', context)



class MessageView(View):
    template_name = "index.html"


    def get(self, request):
        web_content = WebContent.objects.filter().first()
        portfolio = Portfolio.objects.all()
        context = {
            'content': web_content,
            'portfolio': portfolio,

        }
        return redirect('/')

    def post(self, request):
        web_content = WebContent.objects.filter().first()
        portfolio = Portfolio.objects.all()
        context = {
            'content': web_content,
            'portfolio': portfolio,

        }
        msg = Message()
        msg.name = request.POST['name']
        msg.email = request.POST['email']
        msg.message = request.POST['message']
        d = get_date(self.request.GET.get('month', None))
        cal = Calendar(d.year, d.month)
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        context['done'] = 'success'
        msg.save()
        return render(request, self.template_name, context)


class EventView(View):
    template_name = "index.html"


    def get(self, request, d):
        selected_date = d.split('-')
        curr_date = datetime.now().date()
        web_content = WebContent.objects.filter().first()
        portfolio = Portfolio.objects.all()
        context = {
            'content': web_content,
            'portfolio': portfolio,

        }
        dt = date(int(selected_date[2]),int(selected_date[1]),int(selected_date[0]))
        if(curr_date>dt):
            d = get_date(self.request.GET.get('month', None))
            cal = Calendar(d.year, d.month)
            html_cal = cal.formatmonth(withyear=True)
            context['calendar'] = mark_safe(html_cal)
            context['prev_month'] = prev_month(d)
            context['next_month'] = next_month(d)
            context['wrong_date'] = 'Please select future day for appointment!'
            return render(request, self.template_name, context)
        context['date'] = d
        return render(request, self.template_name, context)

    def post(self, request, d):
        web_content = WebContent.objects.filter().first()
        portfolio = Portfolio.objects.all()
        context = {
            'content': web_content,
            'portfolio': portfolio,

        }
        curr_date = get_date(self.request.GET.get('month', None))
        cal = Calendar(curr_date.year, curr_date.month)
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(curr_date)
        context['next_month'] = next_month(curr_date)

        e = Event()
        e.email = request.POST['email']
        e.start_time = request.POST['start_time']
        e.end_time = request.POST['end_time']
        x = d.split('-')
        e.date = datetime(int(x[2]), int(x[1]), int(x[0]))


        # check if event collides

        all_events = Event.objects.filter(date=e.date, start_time__lte=e.end_time, end_time__gte=e.start_time)
        if(all_events):
            context['fail'] = 'fail'
        else:
            context['booked'] = 'success'
            e.save()

        return render(request, self.template_name, context)





def index(request):
    return redirect('admin:index')

contact/templates/cal.html
<!DOCTYPE html>
{% load static %}

	<a class="btn btn-info left" id="lb" href="{% url 'contact:calendar' %}?{{ prev_month }}#cal" style="display: none;"> Previous Month </a>
    <a class="btn btn-info right" id="rb" style="display: none;" href="{% url 'contact:calendar' %}?{{ next_month }}#cal"> Next Month </a>
<style>
    .month{
        text-align: center;
        
    }
    th{
        padding: 4px 14px;
        color: var(--main-gray);
        border: 1px solid black;
        
    }
    td{
        padding: 4px 14px;
        border:1px solid black;
        /* border-top: none; */
        /* border-bottom: none; */
    }
    a{
        color: #0465b9;
    }
    .datenum:hover{
        transform: scale(1.2);
        background-color: #830432;
        color: white;
        border-radius: 50%;
        padding:5px;
    }
</style>

<table>
 {{calendar}}
</table>
<script>
    var v = document.getElementById("lb").getAttribute("href");
    var x = document.getElementById("rb").getAttribute("href");
    document.getElementById("left").setAttribute('href',v);
    document.getElementById("right").setAttribute('href',x);

</script>
<!-- <div>
    
<br>
<a class="btn btn-info right" href="{% url 'contact:event_new' %}"> New Event </a>

</div> -->
<!-- 
<div class="clearfix">
    <a class="btn btn-info left" href="{% url 'contact:calendar' %}"> Calendar </a>
  </div>
  
  {% if form.errors %}
      {% for field in form %}
          {% for error in field.errors %}
              <div class="alert alert-danger">
                  {{ field.label }} <strong>{{ error|escape }}</strong>
              </div>
          {% endfor %}
      {% endfor %}
      {% for error in form.non_field_errors %}
          <div class="alert alert-danger">
              {{ field.label }} <strong>{{ error|escape }}</strong>
          </div>
      {% endfor %}
  {% endif %}
  
  <form method="post">
    {% csrf_token %}
    <table class="form form-table">
      {{ form }}
      <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
    </table>
  </form> -->

</html>

contact/templates/index.html
<!DOCTYPE html>
{% extends "base_dynamic.html" %}
{% load static %}
{% block conten%}

{% include 'cal.html' %}
{% if date %}


<div class="col-xl-6 mb-5">
    <h2 class="tm-color-primary tm-section-title mb-4">Request Appointment</h2>

    <div class="tm-contact-form-wrap">

      <form action="{% url 'contact:event-check' date %}#cal" method="POST" class="tm-contact-form">
        {% csrf_token %}

  
        <div class="form-group">
            <small style="color: red;">Date: {{date}} <a href="{% url 'contact:index' %}#cal" type="button" class="btn btn-danger btn-xs">< Calendar</a></small>
        </div>
        <div class="form-group">
            <input type="email" id="email" name="email" class="form-control rounded-0 border-top-0 border-right-0 border-left-0" placeholder="Your Email" required="" />
          </div>
          <div class="form-group">
            <small>Start time:</small><br>
            <input type="time" id="start_time" name="start_time" required>
        </div>
        <div class="form-group">
            <small>End time:</small><br>
            <input type="time" id="end_time" name="end_time" required>
        </div>
  
          <div class="form-group mb-0">
            {% if fail %}
            <div class="alert alert-danger">
              <strong>Not Booked!</strong> This slot is reserved. Please choose another time!
            </div>
            {% endif %}
            {% if success %}
            <div class="alert alert-success">
              <strong>Success!</strong> Your request has been received. Our team will contact you for confirmation!
            </div>
            {% endif %}

            <button  id="eve" type="submit" class="btn rounded-0 d-block ml-auto tm-btn-primary">
              Book Appointment
            </button>
          </div>
        </form>
    </div>                    
  </div>

{% endif %}
{% if fail %}
<div class="alert alert-danger">
  <strong>Not Booked!</strong> This slot is reserved. Please choose another time!
</div>
{% endif %}
{% if booked %}
<div class="alert alert-success">
  <strong>Success!</strong> Your request has been received. Our team will contact you for confirmation!
</div>
{% endif %}
{% if wrong_date %}
<div id="eve" class="alert alert-danger">
  <strong>Date Incorrect!</strong> Please select future day for appointment.
</div>
{% endif %}
{% endblock %}


</html>